
CREATE TABLE TASK_FILES (
    ID           NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TASK_ID      NUMBER,
    FILE_NAME    VARCHAR2(255),
    MIME_TYPE    VARCHAR2(100),
    FILE_BLOB    BLOB,
    UPLOADED_BY  VARCHAR2(100),
    UPLOADED_AT  DATE DEFAULT SYSDATE
);
