
CREATE TABLE TASK_HISTORY (
    ID            NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TASK_ID       NUMBER,
    ACTION        VARCHAR2(100),
    ACTION_BY     VARCHAR2(100),
    ACTION_DATE   DATE DEFAULT SYSDATE,
    COMMENTS      VARCHAR2(4000)
);
